<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="quizi.css" />
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <div id="startScreen">
      <h1>코딩 실력 퀴즈</h1>
      <button id="startButton">Start</button>
    </div>
    <div class="quiz-container" id="quiz">
      <div class="quiz-header">
        <h2 class="header-txt">코딩 Quiz</h2>
      </div>
      <div class="quiz-body">
        <h2 id="question">Question Text</h2>
        <ul>
          <li>
            <input type="radio" name="answer" id="a" class="answer" />
            <label for="a" id="a_text"> Questions </label>
          </li>
          <li>
            <input type="radio" name="answer" id="b" class="answer" />
            <label for="b" id="b_text"> Questions </label>
          </li>
          <li>
            <input type="radio" name="answer" id="c" class="answer" />
            <label for="c" id="c_text"> Questions </label>
          </li>
          <li>
            <input type="radio" name="answer" id="d" class="answer" />
            <label for="d" id="d_text"> Questions </label>
          </li>
        </ul>
      </div>
      <div id="quiz-footer">
        <div class="quiz-details"></div>
        <button type="button" id="btn">Submit</button>
      </div>
    </div>
    <script src="quizi.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
      $("#startButton").click(function () {
        $("#startScreen").hide();
        $("#gameScreen").show();
      });
      document.getElementById("startButton").onclick = function () {
        document.getElementById("btn").style.visibility = "visible";
      };
    </script>
  </body>
</html>
# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
